"""jqv-27b recipe: CPU tests with a fake tokenizer and golden prompt texts.

The GOLDEN prompt texts were generated by running jqv's own native-v1 code
(jqv/prompt.py PromptBuilder.prefix_text/suffix_text, jqv/systemone.py
render_state/build_question; prompt hash 4f85a0b34776) on the request bodies
below, with a stub tokenizer that is only used for label-token lookup.
"""

import json

import pytest

from instinct.recipes.base import Encoded
from instinct.recipes.jqv_27b import PROMPT_HASH, RECIPE, prefix_text, suffix_text

GOLDEN = {
    "choice": {
        "body": {"state": {"doc": "Alpha é", "n": [1, 2]}, "questions": {"q": {"type": "choice", "instructions": "  Which fits?\n", "criteria": {"red": "Warm colour", "blue": "Cool colour", "green": "Leaf colour"}}}},
        "prefix": "<|im_start|>system\nYou are a decision model. Read the document, then answer each question by choosing exactly one option. Reply with the option letter only.<|im_end|>\n<|im_start|>user\nDocument:\n{\n  \"doc\": \"Alpha é\",\n  \"n\": [\n    1,\n    2\n  ]\n}\n\n",
        "suffix": "Question:\nWhich fits?\n\nOptions:\nA. red: Warm colour\nB. blue: Cool colour\nC. green: Leaf colour\n\nAnswer with the letter only.<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\nAnswer:",
    },
    "noul": {
        "body": {"state": "The sky is clear.", "questions": {"q": {"type": "noul", "instructions": "Is it sunny?", "criteria": {"true": "It is sunny", "false": "It is not sunny"}}}},
        "prefix": "<|im_start|>system\nYou are a decision model. Read the document, then answer each question by choosing exactly one option. Reply with the option letter only.<|im_end|>\n<|im_start|>user\nDocument:\nThe sky is clear.\n\n",
        "suffix": "Question:\nIs it sunny?\n\nOptions:\nA. no: It is not sunny\nB. yes: It is sunny\n\nAnswer with the letter only.<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\nAnswer:",
    },
    "noul_bare": {
        "body": {"state": "The sky is clear.", "questions": {"q": {"type": "noul", "instructions": "Is it sunny?"}}},
        "prefix": "<|im_start|>system\nYou are a decision model. Read the document, then answer each question by choosing exactly one option. Reply with the option letter only.<|im_end|>\n<|im_start|>user\nDocument:\nThe sky is clear.\n\n",
        "suffix": "Question:\nIs it sunny?\n\nOptions:\nA. no\nB. yes\n\nAnswer with the letter only.<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\nAnswer:",
    },
    "score": {
        "body": {"state": "Service was fine.", "questions": {"q": {"type": "score", "instructions": "Rate the service.", "criteria": ["Terrible", "Okay", "Great"]}}},
        "prefix": "<|im_start|>system\nYou are a decision model. Read the document, then answer each question by choosing exactly one option. Reply with the option letter only.<|im_end|>\n<|im_start|>user\nDocument:\nService was fine.\n\n",
        "suffix": "Question:\nRate the service.\n\nOptions:\nA. 0: Terrible\nB. 1: Okay\nC. 2: Great\n\nAnswer with the letter only.<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\nAnswer:",
    },
}


class FakeTokenizer:
    """One id per character; " X" is a single token (1000 + ord(X))."""

    all_special_ids = [0]

    def encode(self, text, add_special_tokens=False):
        if len(text) == 2 and text[0] == " " and text[1].isalpha():
            return [1000 + ord(text[1])]
        return [ord(c) for c in text]


def _text(encoded):
    return "".join(chr(i) for i in encoded.input_ids)


def _records(name):
    (qid, kind, record), = RECIPE.records(GOLDEN[name]["body"])
    return record


def _prompt(name):
    record = _records(name)
    (order,) = RECIPE.orders(record)
    return record, order, RECIPE.encode(FakeTokenizer(), record, order)


def test_identity():
    assert RECIPE.name == "instinct" and RECIPE.temperature == 1.0
    assert RECIPE.readout == "full_head" and RECIPE.max_length == 32768
    assert RECIPE.revision == "1d4bf0f2ff6012fd82039f2fa52739d0dd7c60c0"
    assert PROMPT_HASH in RECIPE.extra["prompt_version"]


@pytest.mark.parametrize("name", ["choice", "noul", "noul_bare", "score"])
def test_golden_prompt_text(name):
    _, _, encoded = _prompt(name)
    assert _text(encoded) == GOLDEN[name]["prefix"] + GOLDEN[name]["suffix"]
    assert len(encoded.input_ids) == len(GOLDEN[name]["prefix"]) + len(GOLDEN[name]["suffix"])


def test_layout_helpers_match_golden():
    for entry in GOLDEN.values():
        assert entry["prefix"] == prefix_text(json.dumps(entry["body"]["state"], ensure_ascii=False, indent=2)
                                              if not isinstance(entry["body"]["state"], str) else entry["body"]["state"])


def test_choice_labels_and_order():
    record, order, encoded = _prompt("choice")
    assert order == ["red", "blue", "green"] == encoded.candidates
    assert encoded.label_token_ids == [1000 + ord(c) for c in "ABC"]
    assert encoded.readout_index == -1 and isinstance(encoded, Encoded)


def test_noul_shown_as_no_yes_but_record_stays_canonical():
    record, order, encoded = _prompt("noul")
    assert [c["id"] for c in record["criteria"]] == ["yes", "no"]
    assert order == encoded.candidates == ["no", "yes"]
    assert RECIPE.merge(record, [encoded], [[0.0, 0.0]]) == [0.5, 0.5]
    # logits are ordered A="no", B="yes"; mass on "yes" comes back under id "yes"
    yes, no = RECIPE.merge(record, [encoded], [[0.0, 2.0]])
    assert yes > no


def test_score_is_choice_with_level_ids():
    record, order, encoded = _prompt("score")
    assert record["primitive"] == "choice" and order == ["0", "1", "2"]


def test_structured_state_is_pretty_printed():
    record = _records("choice")
    assert record["state"] == json.dumps(GOLDEN["choice"]["body"]["state"], ensure_ascii=False, indent=2)


def test_length_limit_and_bad_order():
    record, order, _ = _prompt("choice")
    small = type(RECIPE)(**{**RECIPE.__dict__, "max_length": 10})
    with pytest.raises(ValueError):
        small.encode(FakeTokenizer(), record, order)
    with pytest.raises(ValueError):
        RECIPE.encode(FakeTokenizer(), record, ["red", "blue"])


def test_multi_token_letter_rejected():
    class Bad(FakeTokenizer):
        def encode(self, text, add_special_tokens=False):
            return [1, 2] if text == " C" else super().encode(text)

    record, order, _ = _prompt("choice")
    with pytest.raises(ValueError):
        RECIPE.encode(Bad(), record, order)
